name: Mirror to GitLab

on:
  push:
    branches:
      - KATCHUP-9-set-up-ci-cd

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.name "kylesung0520"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/katchup/katchup.git
          git push --force gitlab HEAD:KATCHUP-9-set-up-ci-cd
